# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lianjia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chengjiao_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fang_key', models.TextField(unique=True)),
                ('fang_desc', models.TextField()),
                ('fang_url', models.TextField()),
                ('xiaoqu_name', models.TextField()),
                ('region', models.TextField()),
                ('subregion', models.TextField()),
                ('transaction_date', models.TextField()),
                ('price_pre', models.TextField()),
                ('price', models.IntegerField()),
                ('louceng', models.TextField()),
                ('chaoxiang', models.TextField()),
                ('zhuangxiu', models.TextField()),
                ('subway_info', models.TextField()),
                ('property_years', models.TextField()),
                ('created_date', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
