# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lianjia', '0003_auto_20170826_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fang_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fang_key', models.TextField(null=True)),
                ('fang_desc', models.TextField(null=True)),
                ('huxing', models.TextField(null=True)),
                ('mianji', models.TextField(null=True)),
                ('louceng', models.TextField(null=True)),
                ('chaoxiang', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('price_pre', models.TextField(null=True)),
                ('fang_url', models.TextField(null=True)),
                ('xiaoqu_key', models.TextField(null=True)),
                ('xiaoqu_name', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('subregion', models.TextField(null=True)),
                ('built_time', models.TextField(null=True)),
                ('subway_info', models.TextField(null=True)),
                ('haskey', models.TextField(null=True)),
                ('property_years', models.TextField(null=True)),
                ('created_date', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fang_xiaoqu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoqu_key', models.TextField(null=True)),
                ('xiaoqu_name', models.TextField(null=True)),
                ('xiaoqu_url', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('subregion', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('built_time', models.TextField(null=True)),
                ('subway_info', models.TextField(null=True)),
                ('onsale_num', models.IntegerField(null=True)),
                ('xiaoqu_fanglist_url', models.TextField(null=True)),
                ('created_date', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fang_xiaoqu',
            unique_together=set([('xiaoqu_key', 'created_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='fang_list',
            unique_together=set([('fang_key', 'created_date')]),
        ),
    ]
