# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lianjia', '0004_auto_20170826_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='fang_list',
            name='is_new',
            field=models.TextField(null=True),
        ),
    ]
